//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cjelina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cjelina()
        {
            this.ispit = new HashSet<ispit>();
        }
    
        public int cjelina_id { get; set; }
        public string naziv_cjeline { get; set; }
        public int predmet_id { get; set; }
        public int razred_id { get; set; }
    
        public virtual predmet predmet { get; set; }
        public virtual razred razred { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ispit> ispit { get; set; }
    }
}
