//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class dan_odgovor
    {
        public int korisnik_id { get; set; }
        public int ponudeni_odgovor_id { get; set; }
        public System.DateTime datum_vrijeme { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        public virtual ponudeni_odgovor ponudeni_odgovor { get; set; }
    }
}
