//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaduzen_za
    {
        public int korisnik_id { get; set; }
        public int razred_id { get; set; }
        public int predmet_id { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        public virtual predmet predmet { get; set; }
        public virtual razred razred { get; set; }
    }
}
