//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class cjeline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cjeline()
        {
            this.ispitis = new HashSet<ispiti>();
        }
    
        public int cjelina_id { get; set; }
        public string naziv_cjeline { get; set; }
        public int predmet_id { get; set; }
        public int razred_id { get; set; }
    
        public virtual predmeti predmeti { get; set; }
        public virtual razredi razredi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ispiti> ispitis { get; set; }
    }
}
