//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ispiti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ispiti()
        {
            this.izabraos = new HashSet<izabrao>();
            this.pitanjas = new HashSet<pitanja>();
        }
    
        public int ispit_id { get; set; }
        public string naziv_ispita { get; set; }
        public int cjelina_id { get; set; }
    
        public virtual cjeline cjeline { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izabrao> izabraos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pitanja> pitanjas { get; set; }
    }
}
