//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Enitities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KvizZnanjaEntities : DbContext
    {
        public KvizZnanjaEntities()
            : base("name=KvizZnanjaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cjeline> cjelines { get; set; }
        public virtual DbSet<dani_odgovori> dani_odgovori { get; set; }
        public virtual DbSet<ispiti> ispitis { get; set; }
        public virtual DbSet<izabrao> izabraos { get; set; }
        public virtual DbSet<korisnici> korisnicis { get; set; }
        public virtual DbSet<pitanja> pitanjas { get; set; }
        public virtual DbSet<ponudeni_odgovori> ponudeni_odgovori { get; set; }
        public virtual DbSet<predmeti> predmetis { get; set; }
        public virtual DbSet<razredi> razredis { get; set; }
        public virtual DbSet<skole> skoles { get; set; }
        public virtual DbSet<tipovi_korisnika> tipovi_korisnika { get; set; }
        public virtual DbSet<zaduzen_za> zaduzen_za { get; set; }
    }
}
