//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pitanja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pitanja()
        {
            this.ponudeni_odgovori = new HashSet<ponudeni_odgovori>();
        }
    
        public int pitanje_id { get; set; }
        public string tekst_pitanja { get; set; }
        public int ispit_id { get; set; }
        public int kreirao_korisnik_id { get; set; }
    
        public virtual ispiti ispiti { get; set; }
        public virtual korisnici korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponudeni_odgovori> ponudeni_odgovori { get; set; }
    }
}
