//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Enitities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ponudeni_odgovori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ponudeni_odgovori()
        {
            this.dani_odgovori = new HashSet<dani_odgovori>();
        }
    
        public int ponudeni_odgovor_id { get; set; }
        public string tekst_odgovora { get; set; }
        public byte tocan { get; set; }
        public int pitanje_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dani_odgovori> dani_odgovori { get; set; }
        public virtual pitanja pitanja { get; set; }
    }
}
